"""empty message

Revision ID: 5947e37b402e
Revises: 583e227e26d1
Create Date: 2024-01-01 23:21:04.446423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5947e37b402e'
down_revision = '583e227e26d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replies',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('reply_text', sa.Text(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('movie_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('replies')
    # ### end Alembic commands ###
