"""empty message

Revision ID: eeb2354bef28
Revises: 4917972bb990
Create Date: 2023-12-12 00:03:35.387827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeb2354bef28'
down_revision = '4917972bb990'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('release', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies')
    # ### end Alembic commands ###
