"""empty message

Revision ID: f2f3fca91a50
Revises: 5947e37b402e
Create Date: 2024-01-01 23:23:55.414524

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2f3fca91a50'
down_revision = '5947e37b402e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_id', sa.BigInteger(), nullable=False))
        batch_op.drop_constraint('replies_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'reviews', ['review_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.drop_column('movie_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movie_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('replies_ibfk_1', 'movies', ['movie_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.drop_column('review_id')

    # ### end Alembic commands ###
